project:
  type: website
  output-dir: docs
  render: 
  - src/smart_cities.qmd
  - src/why_cities.qmd
  - src/intro_networks.qmd
  - src/network_science.qmd
  - src/diversity.qmd
  - src/apis.Rmd
  - src/network_analysis.Rmd
  - src/network_models.Rmd
  - src/description.qmd
  - index.qmd
  - src/syllabus.qmd
  - src/readings.qmd
  - src/author.qmd

website:
  title: "Urban analytics and city science"
  sidebar:
    tools:
      - icon: github
        href: https://github.com/etranos/urban_analytics_city_science
    style: "docked"
    search: false
    contents:
      - section: "Content"
        contents:
          - src/description.qmd
          - src/syllabus.qmd
          - src/readings.qmd
      - section: "Lectures"
        contents:
          - src/why_cities.qmd
          - src/smart_cities.qmd
          - text: "Networks: an introduction"
            file: src/intro_networks.qmd
          - src/network_science.qmd
          - src/diversity.qmd
      - section: "Practicals"
        contents:
          - src/apis.Rmd
          - src/network_analysis.Rmd
          - src/network_models.Rmd
      - section: "Unit leader"
        contents: 
          - text: "Professor Emmanouil Tranos"
            file: src/author.qmd
          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

