project:
  type: website
  output-dir: docs
  render: 
  - src/L1_why_cities.qmd
  - src/L2_smart_cities.qmd
  - src/L3_intro_networks.qmd
  - src/L4_network_science.qmd
  - src/L5_transport_geography.qmd
  - src/L6_diversity.qmd
  - src/P1_apis.Rmd
  - src/P2_network_analysis.Rmd
  - src/P3_street_networks.Rmd
  - src/P4_network_models.Rmd
  - src/P5_sim.Rmd
  - src/P6_accessibility_full.Rmd
  - src/P7_causality.Rmd
  - src/description.qmd
  - index.qmd
  - src/syllabus.qmd
  - src/readings.qmd 
  - assignments/project.md


website:
  title: "Urban analytics and city science"
  sidebar:
    tools:
      - icon: github
        href: https://github.com/etranos/urban_analytics_city_science
    style: "docked"
    search: false
    contents:
      - section: "Content"
        contents:
          - src/description.qmd
          - src/syllabus.qmd
          - src/readings.qmd
          - text: "Assessment"
            file: assignments/project.md
      - section: "Lectures"
        contents:
          - src/L1_why_cities.qmd
          - src/L2_smart_cities.qmd
          - text: "L2: Networks: an introduction"
            file: src/L3_intro_networks.qmd
          - src/L4_network_science.qmd
          - src/L5_transport_geography.qmd
          - src/L6_diversity.qmd
          - text: "L7: Urban policies and causality"
            file: src/L7_Urban_policy___causal_design.pdf
      - section: "Practicals"
        contents:
          - src/P1_apis.Rmd
          - src/P2_network_analysis.Rmd
          - src/P3_street_networks.Rmd
          - src/P4_network_models.Rmd
          - src/P5_sim.Rmd
          - src/P6_accessibility_full.Rmd
          - text: "P7: Causal design and urban policy evaluation"
            file: src/P7_causality.Rmd
      - section: "Unit leader"
        contents: 
          - text: "Professor Emmanouil Tranos"
            file: https://etranos.info/
          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

