---
title: "Syllabus"
bibliography: references.bib
editor: source
---
**Compressed Schedule** 

| **Week count** | **Week starting** | **Thursday date** |                **Lecture content**                | **Practical Content** | **Note**                                                 |
|:--------------:|:-----------------:|:-----------------:|:-------------------------------------------------:|:---------------------:|----------------------------------------------------------|
|     Week 1     |     25/09/2023    |     28/09/2023    |             Introduction + Lecture 1              |           -           |                                                          |
|     Week 2     |     02/10/2023    |     05/10/2023    |                     Lecture 2                     |      Practical 1      |                                                          |
|     Week 3     |     09/10/2023    |     12/10/2023    |                     Lecture 3                     |      Practical 2      |                                                          |
|     Week 4     |     16/10/2023    |     19/10/2023    |                                                   |      Practical 3      |                                                          |
|     Week 5     |     23/10/2023    |     26/10/2023    |                     Lecture 4                     |      Practical 3      |                                                          |
|     Week 6     |     30/10/2023    |     02/11/2023    |                                                   |      Practical 4      |                                                          |
|     Week 7     |     06/11/2023    |     09/11/2023    |                    Reading week                   |                       | Submission of data selection minireport by 12th November |
|     Week 8     |     13/11/2023    |     16/11/2023    |                     Lecture 5                     |      Practical 5      |                                                          |
|     Week 9     |     20/11/2023    |     23/11/2023    |                                                   |      Practical 5      |                                                          |
|     Week 10    |     27/11/2023    |     30/11/2023    |                     Lecture 6                     |      Practical 6      |                                                          |
|     Week 11    |     04/12/2023    |     07/12/2023    |                                                   |      Practical 6      |                                                          |
|     Week 12    |     11/12/2023    |     14/12/2023    |  Mini Causal lecture + catching up on practicals  |                       | Lecture 7 and   Practical 7 is optional          |
| **Christmas** |   **Christmas**  |   **Christmas**  |                   **Christmas**                  |     **Christmas**    |                      **Christmas**                      |
|                |                   |     11/01/2024    | Assignment submission - accounts for 100% of mark |                       |                                                          |

**Decompressed Schedule**

1.  Lecture 1: [Cities, a very very brief introduction](L1_why_cities.qmd){target="_blank"}

    Why do cities exist? One cannot study, analyse and model cities and systems of cities unless they know their fundamental attributes, and the reasons why cities have been developed at the first instance.

2.  Lecture 2: [Smart cities, urban big data, digital twins and other buzz terms](L2_smart_cities.qmd){target="_blank"}

    -   Practical 1: [APIs and urban data](P1_apis.Rmd){target="_blank"}

    <!-- 2. digital traces **P**: ??? think of traces -->

    <!-- 3. Social Media **P**: Twitter -->

    How do digital technologies change cities? How does their usage actually enables citizens to act as sensors? And, how do these changes affect urban research? We will first approach these issues from a theoretical perspective and then utilise such free and open urban data using APIs.

3.  Lecture 3: [Networks: an introduction](L3_intro_networks.qmd){target="_blank"}

    Networks are everywhere! After this lecture you will hopefully start seeing them.

    - Practical 2: [Network analysis practical: networks of cities](P2_network_analysis.Rmd){target="_blank"}

4.  Practical 3: [Street network analysis practical: networks within cities](P3_street_networks.Rmd){target="_blank"}

    These two practical sessions will put into practise your newly acquired network understanding of cities.

<!-- -   Csárdi, G., Nepusz, T., & Airoldi, E. M. (2016). Statistical network analysis with igraph. Springer. Available online at https://www.uni-due.de/hummell/sna/igraph/docs/.BookDraft-CsardiNepuszAiroldi2016.pdf. \[*methods*\] -->

<!-- -   Degree distribution (see help_degree_sistribution.Rmd) -->

5. Lecture 4: [Network science, urban laws and scaling](L4_network_science.qmd){target="_blank"}

    - Continue work on Practical 3

6.  Practical 4: [Build and compare models](P4_network_models.Rmd){target="_blank"}

    Moving from network analysis to network science with clear urban applications.
    
7.  Reading week. You will be asked to submit short mini report (deadline 12th November) in which you will explore data set suitable for final assignment. This is not marked, contributes 0% to your final mark, but completing this will enable you to get a feedback and consultation on your choice of data set and your final project topic.

8.  Lecture 5: [Methods in transport geography](L5_transport_geography.qmd){target="_blank"}

    Same methods, different facets of urban research. This part of the unit will allow you to apply your network skills to answer transport related questions. It will also make the transition from networks to flows.

    - Practical 5: [Spatial interaction modelling](P5_sim.Rmd){target="_blank"} : You ve'learned how to analyse networks, now you can learn how to analyse and 
    model flows. Do you see the parallel?

<!-- For spatial interactions: - Bettencourt 2021 8.1.3 for Maximum entropym radiation and a variant of urban scaling - https://www.nature.com/articles/nature10856 -->

<!-- For network analysis: - Barthelemy 2018 Ch. 7. It has examples for road and subway studies + some policy elements. No code. -->

<!-- 8.  Networks small scale / Spatial networks -->

<!--     -   https://cran.r-project.org/web/packages/sfnetworks/ -->

<!--     -   Boeing -->

<!--     -   https://osf.io/78yub/ -->

<!--     -   Lovelace's book, Geocomputation with R https://geocompr.robinlovelace.net/ -->

<!-- use sfnetworks as it contains igraph. Use the vignettes. https://cran.r-project.org/web/packages/sfnetworks/index.html -->

9.  Continue work on Practical 5: [Spatial interaction modelling](P5_sim.Rmd){target="_blank"}

<!-- @kolaczyk2020statistical Ch 9 -->

10.  Lecture 6: [Diversity in cities](L6_diversity.qmd){target="_blank"}

      Why is diversity important in cities and how do we measure it?
      
      - Practical 6: [Accessibility](P6_accessibility_full.Rmd){target="_blank"}

11.   Continue work on Practical 6: [Accessibility](P6_accessibility_full.Rmd){target="_blank"}

12. Lecture 7 + Practical 7: [Urban policies and causality](L6_Urban_policy___causal_design.pdf){target="_blank"} and [Causal design and urban policy evaluation](P7_causality.rmd){target="_blank"}

    this is going to be a brief introduction to causality. The lecture 7 and practical 7 materials are availiable online but are optional and for you to go through if you wish to.
